// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  hero: dynamic(() => import("./Hero")),
  home_section: dynamic(() => import("./HomeSection")),
  projet_section: dynamic(() => import("./ProjetSection")),
  service_list: dynamic(() => import("./ServiceList")),
  service_section: dynamic(() => import("./ServiceSection")),
};
